import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ConfigProvider } from 'antd'
import { StoreProvider } from '@/redux/provider'
import {NextIntlClientProvider, useMessages} from 'next-intl';
import ReactQueryProvider from '@/utils/queryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode,
  params: {locale: string};
}) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <ReactQueryProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <ConfigProvider theme={{hashed: false, token: {
              fontFamily: 'inherit',
              colorPrimary: 'black',
              fontSize: 16, 
            }
            }}>
              <StoreProvider>
                {children}
              </StoreProvider>
            </ConfigProvider>
          </NextIntlClientProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
